#pragma once
class Registry;
class TileData;
class EntityData;
class chunkmap;
class Entity;
class Tile;
class Player;
class EntityManager;
class PlayerManager;
class Room;
class Dimension;
class DimensionAccses;
class World;
namespace executionProses{
    void earlyExecution();
    void tickExecution();
    void randomTick();
    void cleanUpExecution();
};