#pragma once
#include "core/forward.hpp"
#include "eventType.hpp"
#include <unordered_map>
#include <map>
#include "internal/idmaker.hpp"
#include <stdexcept>
#include "entity/component.hpp"
#include "entity/player/component.hpp"
#include "tile/component.hpp"
#include <tuple>